/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.Administrador;

import DAOs.CentroComputoDAO;
import DTOs.CarreraDTO;
import DTOs.CentroComputoDTO;
import DTOs.EstudianteDTO;
import DTOs.UnidadAcademicaDTO;
import Negocio.CentroComputoNegocio;
import excepciones.NegocioException;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FrmAgregarCentroComputo extends javax.swing.JFrame {

    CentroComputoNegocio centroComputoNegocio;
    List<UnidadAcademicaDTO> unidades;

    /**
     * Creates new form AgregarCentroComputo
     */
    public FrmAgregarCentroComputo() {
        initComponents();
        unidades = new ArrayList<>();
        centroComputoNegocio = new CentroComputoNegocio(); // Verifica que esto esté aquí
        cargarUnidades();
    }

    private void cargarUnidades() {
        try
        {
            unidades = centroComputoNegocio.obtenerUnidadesAcademicas(); // Asigna directamente a la lista de instancia
            CBUnidadA.removeAllItems();
            for (UnidadAcademicaDTO unidad : unidades)
            {
                if (unidad.getNombre() != null)
                { // Asegúrate de que el nombre no sea nulo
                    CBUnidadA.addItem(unidad.getNombre());
                } else
                {
                    System.err.println("Unidad académica con nombre nulo encontrada.");
                }
            }
        } catch (NullPointerException e)
        {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e)
        {
            System.err.println("Se produjo un error al cargar las unidades: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        dateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker();
        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LblNombre = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LblContraseñamaestra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TimeInicio = new com.github.lgooddatepicker.components.TimePicker();
        TimeFin = new com.github.lgooddatepicker.components.TimePicker();
        jLabel7 = new javax.swing.JLabel();
        CBUnidadA = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Estudiante");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar Centro Computo");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 28, -1, -1));

        LblNombre.setBackground(new java.awt.Color(255, 255, 255));
        LblNombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 255, -1));

        BtnAgregar.setBackground(new java.awt.Color(102, 153, 255));
        BtnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        BtnAgregar.setText("Agregar Centro Computo");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        jPanel4.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Unidad Academica");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        LblContraseñamaestra.setBackground(new java.awt.Color(255, 255, 255));
        LblContraseñamaestra.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(LblContraseñamaestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 255, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña Maestra");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));
        jPanel4.add(TimeInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 110, 30));
        jPanel4.add(TimeFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 120, 30));

        jLabel7.setText("Hora Fin");
        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        CBUnidadA.setBackground(new java.awt.Color(255, 255, 255));
        CBUnidadA.setForeground(new java.awt.Color(0, 0, 0));
        CBUnidadA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUnidadAActionPerformed(evt);
            }
        });
        jPanel4.add(CBUnidadA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 110, 30));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hora Inicio");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanel4.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        try
        {
            // Obtener los valores ingresados en el formulario
            String nombre = LblNombre.getText();
            String contrMa = LblContraseñamaestra.getText();
            LocalTime horaInicio = TimeInicio.getTime();
            LocalTime horaFin = TimeFin.getTime();

            // Verificar que todos los campos requeridos están llenos
            if (nombre.isEmpty() || contrMa.isEmpty() || horaInicio == null || horaFin == null)
            {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            UnidadAcademicaDTO unidadSeleccionada = (CBUnidadA.getSelectedIndex() != -1)
                    ? unidades.get(CBUnidadA.getSelectedIndex())
                    : null;

            if (unidadSeleccionada != null)
            {
                // Verifica que el nombre de la unidad no sea nulo o vacío
                String nombreUnidad = unidadSeleccionada.getNombre();
                if (nombreUnidad == null || nombreUnidad.isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "La unidad académica seleccionada no tiene un nombre válido.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                // Crear el nuevo Centro de Cómputo
                CentroComputoDTO nuevoCentro = new CentroComputoDTO();
                nuevoCentro.setNombre(nombre);
                nuevoCentro.setContrasenaMaestra(contrMa);
                nuevoCentro.setHoraInicio(horaInicio);
                nuevoCentro.setHoraFin(horaFin);
                nuevoCentro.setUnidadAcademica(unidadSeleccionada);

                // Agregar el nuevo Centro de Cómputo
                centroComputoNegocio.insertarCentroComputo(nuevoCentro);

                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(this, "Centro de Cómputo agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos(); // Método para limpiar los campos después de agregar
            } else
            {
                JOptionPane.showMessageDialog(this, "No se ha seleccionado una unidad académica válida.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NegocioException ex)
        {
            try
            {
                throw new NegocioException(ex.getMessage());
//            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (NegocioException ex1)
            {
                Logger.getLogger(FrmAgregarCentroComputo.class.getName()).log(Level.SEVERE, null, ex1);
            }
        } catch (Exception ex)
        {
            Logger.getLogger(FrmAgregarCentroComputo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ocurrió un error al agregar el centro de cómputo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void limpiarCampos() {
        LblNombre.setText("");
        LblContraseñamaestra.setText("");
        TimeInicio.setTime(null);
        TimeFin.setTime(null);
        CBUnidadA.setSelectedIndex(-1); // Reiniciar el combo box
    }

    private void CBUnidadAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUnidadAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBUnidadAActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        FrmCentroComputo fcc = new FrmCentroComputo();
        fcc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmAgregarCentroComputo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmAgregarCentroComputo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmAgregarCentroComputo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmAgregarCentroComputo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarCentroComputo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JComboBox<String> CBUnidadA;
    private javax.swing.JTextField LblContraseñamaestra;
    private javax.swing.JTextField LblNombre;
    private com.github.lgooddatepicker.components.TimePicker TimeFin;
    private com.github.lgooddatepicker.components.TimePicker TimeInicio;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
