/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.Administrador;

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBloqueos = new javax.swing.JButton();
        btnReporteSucursales = new javax.swing.JButton();
        btnAdministrarFunciones = new javax.swing.JButton();
        btnCatalogoEstudiantes = new javax.swing.JButton();
        btnAdministrarFunciones1 = new javax.swing.JButton();
        btnAdministrarFunciones2 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        btnBloqueos.setBackground(new java.awt.Color(0, 204, 255));
        btnBloqueos.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btnBloqueos.setForeground(new java.awt.Color(0, 0, 51));
        btnBloqueos.setText("Control Bloqueos");
        btnBloqueos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloqueosActionPerformed(evt);
            }
        });
        jPanel1.add(btnBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 260, 50));

        btnReporteSucursales.setBackground(new java.awt.Color(0, 204, 255));
        btnReporteSucursales.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btnReporteSucursales.setForeground(new java.awt.Color(0, 0, 51));
        btnReporteSucursales.setText("Reporte Centro De Cómputos");
        btnReporteSucursales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReporteSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteSucursalesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporteSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 290, 50));

        btnAdministrarFunciones.setBackground(new java.awt.Color(0, 204, 255));
        btnAdministrarFunciones.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btnAdministrarFunciones.setForeground(new java.awt.Color(0, 0, 51));
        btnAdministrarFunciones.setText("Reporte Bloqueos");
        btnAdministrarFunciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministrarFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarFuncionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdministrarFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 260, 50));

        btnCatalogoEstudiantes.setBackground(new java.awt.Color(51, 204, 255));
        btnCatalogoEstudiantes.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btnCatalogoEstudiantes.setForeground(new java.awt.Color(0, 0, 51));
        btnCatalogoEstudiantes.setText("Gestión Estudiantes");
        btnCatalogoEstudiantes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCatalogoEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoEstudiantesActionPerformed(evt);
            }
        });
        jPanel1.add(btnCatalogoEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 260, 50));

        btnAdministrarFunciones1.setBackground(new java.awt.Color(0, 204, 255));
        btnAdministrarFunciones1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btnAdministrarFunciones1.setForeground(new java.awt.Color(0, 0, 51));
        btnAdministrarFunciones1.setText("Administrar Centros De Cómputo");
        btnAdministrarFunciones1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministrarFunciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarFunciones1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdministrarFunciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 330, 50));

        btnAdministrarFunciones2.setBackground(new java.awt.Color(0, 204, 255));
        btnAdministrarFunciones2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btnAdministrarFunciones2.setForeground(new java.awt.Color(0, 0, 51));
        btnAdministrarFunciones2.setText("Reporte Carreras");
        btnAdministrarFunciones2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministrarFunciones2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarFunciones2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdministrarFunciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 260, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrarFunciones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarFunciones2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarFunciones2ActionPerformed

    private void btnAdministrarFunciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarFunciones1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarFunciones1ActionPerformed

    private void btnCatalogoEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoEstudiantesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCatalogoEstudiantesActionPerformed

    private void btnAdministrarFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarFuncionesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAdministrarFuncionesActionPerformed

    private void btnReporteSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteSucursalesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnReporteSucursalesActionPerformed

    private void btnBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloqueosActionPerformed

    }//GEN-LAST:event_btnBloqueosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarFunciones;
    private javax.swing.JButton btnAdministrarFunciones1;
    private javax.swing.JButton btnAdministrarFunciones2;
    private javax.swing.JButton btnBloqueos;
    private javax.swing.JButton btnCatalogoEstudiantes;
    private javax.swing.JButton btnReporteSucursales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
