/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.Computadora;

import DTOs.ComputadoraDTO;
import ENUM_P.Estado;
import Negocio.CentroComputoNegocio;
import Negocio.ComputadoraNegocio;
import javax.swing.JOptionPane;
import presentacion.Estudiante.FrmIngresar;

/**
 *
 * @author user
 */
public class FrmLiberarComputadora extends javax.swing.JFrame {

    CentroComputoNegocio centroComputoNegocio;
    ComputadoraNegocio computadoraNegocio;
    FrmIngresar frmIngresar = new FrmIngresar();
    FrmDesbloquear frmDesbloquear = new FrmDesbloquear();

    String idStr;
    
    /**
     * Creates new form FrmLiberarComputadora
     */
    public FrmLiberarComputadora(String idStr) {
        initComponents();
        centroComputoNegocio = new CentroComputoNegocio();
        computadoraNegocio = new ComputadoraNegocio();
        setLocationRelativeTo(null);
        this.idStr = idStr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLiberar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnLiberar.setBackground(new java.awt.Color(102, 204, 255));
        btnLiberar.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLiberar.setForeground(new java.awt.Color(255, 255, 255));
        btnLiberar.setText("Liberar");
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed

        
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            long idEstudiante = Long.parseLong(idStr);
            // Lógica para liberar la computadora
            ComputadoraDTO computadoraOcupada = computadoraNegocio.obtenerComputadoraPorEstudiante(idEstudiante);

            if (computadoraOcupada != null) {
                long idComputadora = computadoraOcupada.getId(); // Obtener el ID
                Estado nuevoEstado = Estado.DISPONIBLE; // Definir el nuevo estado

                // Actualizar la computadora en la base de datos
                computadoraNegocio.actualizarComputadora(idComputadora, nuevoEstado);
                JOptionPane.showMessageDialog(this, "Computadora liberada exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ninguna computadora ocupada por este ID.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al liberar la computadora: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Manda al frmDesbloquear si es necesario
        FrmDesbloquear fdb = new FrmDesbloquear();
        fdb.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnLiberarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLiberarComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLiberarComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLiberarComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLiberarComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrmLiberarComputadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLiberar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
